---
# Start of ELK Automation script
- name: Start of ELK Automation Script
  hosts: localhost
  connection: local
  gather_facts: False
  # EC2 instance module can be referenced and the variables can be filled out below for quick changing
  vars:
    sshkeypair: linkey1
	#Region specific AMI
	amiver: ami-15e9c770
	secgroup: default
	subnetid: subnet-98eb97d5
	
	
  tasks:
   - name: Create EC2 instance
   # Begin module
     ec2:
		aws_access_key: AKIAICVCGAY7BXJGJPRA
		aws_secret_key: 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
		key_name: "{{sshkeypair}}"
		instance_type: t2.micro
		image: "{{amiver}}"
		wait: yes
		#Group is in reference to the security group
		group: "{{secgroup}}"
		count: 1
		vpc_subnet_id: "{{subnetid}}"
		assign_public_ip: yes
	 register: ec2
   
   # Make a group with all the IPs from the instances so we can do stuff to them
   - name: Create group with instance public IPs
     add_host: hostname={{ item.public_ip }} groups=ec2hosts
	 with_items: "{{ ec2.instances }}"
	 